export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";


export const ACCEPT_ORDER_REQUEST = "ACCEPT_ORDER_REQUEST";
export const ACCEPT_ORDER_SUCCESS = "ACCEPT_ORDER_SUCCESS";
export const ACCEPT_ORDER_FAILURE = "ACCEPT_ORDER_FAILURE";

export const DECLINE_ORDER_REQUEST = "DECLINE_ORDER_REQUEST";
export const DECLINE_ORDER_SUCCESS = "DECLINE_ORDER_SUCCESS";
export const DECLINE_ORDER_FAILURE = "DECLINE_ORDER_FAILURE";
